### ISSUE TITLE
Running `docker build` errors on arm64 / Apple M1

### ISSUE THREAD

**Issue by taybenlor** [SebastiaanYN/FFmpeg-WASI#1]
G'day, this is awesome!

I was looking for a WASI build of `ffmpeg` for a demo and stumbled on your repo. It's been super helpful.

I had issues when trying to build `x264` in the `build-deps.sh` script. The error I got was pretty cryptic "No Working C Compiler found". After some googling I figured it might be something to do with arm64, and I was on an M1.

Switching the `Dockerfile` to:

```
FROM --platform=linux/x86_64 ubuntu:20.04 AS setup
```

Worked as a quick fix for me, but [there may be a better fix](https://stackoverflow.com/questions/70141182/build-x264-failed-on-apple-m1-no-working-c-compiler-found).

Thanks again!

**Comment by taybenlor** [comment]
PS: Here's some screenshots of ffmpeg.wasm running in the WASI environment I've been working on: https://twitter.com/taybenlor/status/1571475271760609280?s=20&t=L6y7AzgVqsbD7vm_u9xkuw

**Comment by SebastiaanYN** [comment]
I've included the workaround in the readme
